name: Release to Crates.io

on:
  release:
    types:
      - created

env:
  CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Publish to Crates.io
        run: cargo publish --token ${CRATES_TOKEN}
