name: Run Tests on PR Merge

on:
  pull_request:
    types:
      - opened
      - closed
      - reopened

env:
  CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
