name: Run Tests on PR Merge

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed
env:
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
